include:
  - local: 'ci-templates/docker-build.yml'

build_airflow:
  extends: .build_template
  variables:
    SUBDIR: "airflow"
  rules:
    # Run only after merge (push to main)
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never